apiVersion: v1
kind: PersistentVolume
metadata:
  name: 30gbpv
  labels:
    type: aws
spec:
  storageClassName: manual
  capacity:
    storage: 30Gi
  accessModes:
    - ReadWriteOnce
  awsElasticBlockStore:
    volumeID: "vol-00184d3cb7ff88924"
    fsType: ext4    
